blueprint:
  name: Bambu Lab TP-Link Lightstrip Controller with Progress-Based Color
  description: Control one or more TP-Link light strips with Bambu 3D printer, including progress-based color change
  domain: automation
  source_url: https://github.com/greghesp/ha-bambulab/blob/main/blueprints/wled_controller.yaml
  input:
    printer_status:
      name: Print Status of your Bambu Lab printer
      description: "Select the print status entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    printer_stage:
      name: Current Stage of your Bambu Lab Printer
      description: "Select the printer current stage entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    printer_progress:
      name: Print Progress of your Bambu Lab Printer
      description: "Select the print progress entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    chamber_light:
      name: Chamber Light of your Bambu Lab Printer
      description: "Select the printer chamber light entity."
      selector:
        entity:
          filter:
            domain: light
            integration: bambu_lab
    tplink_lightstrip:
      name: TP-Link Lightstrip
      description: "Select the TP-Link light strip you wish to control."
      selector:
        entity:
          domain: light
          integration: tplink

alias: Bambu Lab TP-Link Lightstrip Controller with Progress-Based Color
description: ""
trigger:
  - platform: state
    entity_id:
      - !input chamber_light
      - !input printer_status
      - !input printer_stage
      - !input printer_progress
    alias: When printer stage, status, chamber light state, or print progress changes
condition: []
action:
  - service: logbook.log
    data:
      name: "TP-Link Lightstrip Automation"
      message: "Triggered with status: {{ states('sensor.skywalker_3d_printer_print_status') }}, stage: {{ states('sensor.skywalker_3d_printer_current_stage') }}, progress: {{ states('sensor.skywalker_3d_printer_print_progress') }}"
  - variables:
      progress: "{{ states('sensor.skywalker_3d_printer_print_progress') | int(0) }}"
      blue_to_green: "{{ (255 * progress / 100) | int }}"
      color: [0, {{ blue_to_green }}, {{ 255 - blue_to_green }}]
  - service: logbook.log
    data:
      name: "TP-Link Lightstrip Progress"
      message: "Calculated progress: {{ progress }}, color: {{ color }}"
  - if:
      - condition: state
        state: "on"
        alias: Chamber light is on
        entity_id: !input chamber_light
      - condition: not
        conditions:
          - condition: state
            entity_id: !input printer_stage
            state: scanning_bed_surface
            alias: Scanning Bed Surface
          - condition: state
            entity_id: !input printer_stage
            state: cleaning_nozzle_tip
            alias: Cleaning Nozzle Tip
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_extrusion
            alias: Calibrating Extrusion
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_extrusion_flow
            alias: Calibrating Extrusion Flow
          - condition: state
            entity_id: !input printer_status
            state: offline
            alias: Printer is off
        alias: And Lidar is NOT on
    then:
      - service: light.turn_on
        data:
          rgb_color:
            - 255
            - 255
            - 255
          brightness_pct: 100
        alias: Turn TP-Link lightstrip on white
        target:
          entity_id: !input tplink_lightstrip
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_filament_runout
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_front_cover_falling
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_nozzle_temperature_malfunction
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_heat_bed_temperature_malfunction
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 169
                    - 0
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to yellow (error)
        alias: Do we need to set color to yellow?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: idle
                  - condition: state
                    entity_id: !input printer_status
                    state: finish
                  - condition: state
                    entity_id: !input printer_status
                    state: offline
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 0
                    - 255
                    - 0
                  brightness: 255
                  effect: Solid
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to green
              - delay:
                  hours: 0
                  minutes: 5
                  seconds: 0
                  milliseconds: 0
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 255
                    - 255
                  brightness: 255
                  effect: Solid
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to white
        alias: Do we need to set color to green?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: auto_bed_leveling
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 0
                    - 0
                    - 255
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to blue
        alias: Do we need to set color to blue?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: heatbed_preheating
                  - condition: state
                    entity_id: !input printer_stage
                    state: heating_hotend
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 169
                    - 0
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to yellow
        alias: Do we need to set color to yellow?
      - choose:
          - conditions:
              - condition: state
                entity_id: !input printer_stage
                state: printing
            sequence:
              - service: logbook.log
                data:
                  name: "TP-Link Lightstrip Color"
                  message: "Setting color to {{ color }} based on progress {{ progress }}"
              - service: light.turn_on
                data_template:
                  rgb_color: "{{ color }}"
                  brightness: 255
                  effect: Solid
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip with progress-based color
        alias: Do we need to set color based on progress?
    else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input tplink_lightstrip
        alias: Turn TP-Link lightstrip off
mode: single
