blueprint:
  name: Bambu Lab TP-Link Lightstrip Controller with Progress Bar
  description: Control a TP-Link light strip with Bambu 3D printer, including a progress bar effect
  domain: automation
  source_url: https://github.com/greghesp/ha-bambulab/blob/main/blueprints/wled_controller.yaml
  input:
    printer_status:
      name: Print Status of your Bambu Lab printer
      description: "Select the print status entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    printer_stage:
      name: Current Stage of your Bambu Lab Printer
      description: "Select the printer current stage entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    printer_progress:
      name: Print Progress of your Bambu Lab Printer
      description: "Select the print progress entity."
      selector:
        entity:
          filter:
            domain: sensor
            integration: bambu_lab
    chamber_light:
      name: Chamber Light of your Bambu Lab Printer
      description: "Select the printer chamber light entity."
      selector:
        entity:
          filter:
            domain: light
            integration: bambu_lab
    tplink_lightstrip:
      name: TP-Link Lightstrip
      description: "Select the TP-Link light strip you wish to control."
      selector:
        entity:
          domain: light
          integration: tplink

alias: Bambu Lab TP-Link Lightstrip Controller with Progress Bar
description: ""
trigger:
  - platform: state
    entity_id:
      - !input chamber_light
      - !input printer_status
      - !input printer_stage
      - !input printer_progress
    alias: When printer stage, status, chamber light state, or print progress changes
condition: []
action:
  - variables:
      progress: "{{ states('!input printer_progress') | int }}"
      total_zones: 50  # Number of addressable zones in the light strip
      zones_on: "{{ (total_zones * progress / 100) | int }}"
      zones_off: "{{ total_zones - zones_on }}"
      color_on: [0, 255, 0]  # Green color for progress
      color_off: [0, 0, 0]  # Off color for remaining zones
  - if:
      - condition: state
        state: "on"
        alias: Chamber light is on
        entity_id: !input chamber_light
      - condition: not
        conditions:
          - condition: state
            entity_id: !input printer_stage
            state: scanning_bed_surface
            alias: Scanning Bed Surface
          - condition: state
            entity_id: !input printer_stage
            state: cleaning_nozzle_tip
            alias: Cleaning Nozzle Tip
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_extrusion
            alias: Calibrating Extrusion
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_extrusion_flow
            alias: Calibrating Extrusion Flow
          - condition: state
            entity_id: !input printer_status
            state: offline
            alias: Printer is off
        alias: And Lidar is NOT on
    then:
      - service: light.turn_on
        data:
          rgb_color:
            - 255
            - 255
            - 255
          brightness_pct: 100
        alias: Turn TP-Link lightstrip on white
        target:
          entity_id: !input tplink_lightstrip
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_filament_runout
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_front_cover_falling
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_nozzle_temperature_malfunction
                  - condition: state
                    entity_id: !input printer_stage
                    state: paused_heat_bed_temperature_malfunction
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 0
                    - 0
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to red
        alias: Do we need to set color to red?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: idle
                  - condition: state
                    entity_id: !input printer_status
                    state: finish
                  - condition: state
                    entity_id: !input printer_status
                    state: offline
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 0
                    - 255
                    - 0
                  brightness: 255
                  effect: Solid
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to green
              - delay:
                  hours: 0
                  minutes: 5
                  seconds: 0
                  milliseconds: 0
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 255
                    - 255
                  brightness: 255
                  effect: Solid
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to white
        alias: Do we need to set color to green?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: auto_bed_leveling
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 0
                    - 0
                    - 255
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to blue
        alias: Do we need to set color to blue?
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input printer_stage
                    state: heatbed_preheating
                  - condition: state
                    entity_id: !input printer_stage
                    state: heating_hotend
            sequence:
              - service: light.turn_on
                data:
                  rgb_color:
                    - 255
                    - 169
                    - 0
                  brightness: 255
                  effect: Blink
                target:
                  entity_id: !input tplink_lightstrip
                alias: Turn on TP-Link lightstrip to yellow
        alias: Do we need to set color to yellow?
      - service: light.turn_on
        data_template:
          entity_id: !input tplink_lightstrip
          brightness: 255
          effect: >
            {% set progress = states('!input printer_progress') | int %}
            {% set total_zones = 50 %}
            {% set zones_on = (total_zones * progress / 100) | int %}
            {% set zones_off = total_zones - zones_on %}
            {% set color_on = [0, 255, 0] %}
            {% set color_off = [0, 0, 0] %}
            {{
              [
                {"transition": 0, "color": color_on, "count": zones_on},
                {"transition": 0, "color": color_off, "count": zones_off}
              ]
            }}
        alias: Update TP-Link lightstrip progress bar
    else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input tplink_lightstrip
        alias: Turn TP-Link lightstrip off
mode: single
